[package]
name = "ancestry-prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = "1.0.108"
ssz-rs = { git = "https://github.com/commonprefix/ssz-rs", branch = "main" }
sync-committee-rs = { package = "sync-committee-primitives", git = "https://github.com/commonprefix/sync-committee-rs", branch = "cp_changes", default-features = false, features = [
    "serialize",
    "mainnet",
] }
